; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "R.E.P.O.Launcher"
#define MyAppVersion "2026.07.02.1844.1"
#define MyAppPublisher "xingKong"
#define MyAppURL "https://github.com/liuxuefeng1997/R.E.P.O.Launcher"
#define MyAppExeName "R.E.P.O.Launcher.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{6D157507-F91D-489E-83F1-46313A8FF9E7}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
;DefaultDirName={reg:SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Steam App 3241660,InstallLocation}
DefaultDirName={code:GetInstallString}
AppendDefaultDirName=no
DirExistsWarning=no
DisableDirPage=auto
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
LicenseFile=X:\Project\IntelliJ_IDEA\repo_launcher\LICENSE
; Remove the following line to run in administrative install mode (install for all users).
PrivilegesRequired=lowest
OutputDir=X:\Project\IntelliJ_IDEA\repo_launcher\.release_build
OutputBaseFilename={#MyAppName}.Installer
SetupIconFile=X:\Project\IntelliJ_IDEA\repo_launcher\sources\repo.ico
SolidCompression=yes
WizardStyle=modern windows11

[code]
function GetInstallString(Param:String): String;
var
  sInstallPath: String;
begin
  sInstallPath := '';
  if RegValueExists(HKLM, 'SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Steam App 3241660', 'InstallLocation') 
  then
  begin
    RegQueryStringValue(HKLM, 'SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Steam App 3241660', 'InstallLocation', sInstallPath)    
  Result := sInstallPath;
  end else 
      begin
  MsgBox('从注册表获取REPO安装目录失败，请手动选择', mbInformation, MB_OK);
  end
end;

function PrepareToInstall(var NeedsRestart: Boolean): String;
var
  ResultCode: Integer;
begin
  Result := '';
  
  // 结束 R.E.P.O.Launcher.exe 进程
  Log('尝试结束 R.E.P.O.Launcher.exe...');
  Exec('taskkill.exe', '/f /im R.E.P.O.Launcher.exe', '', SW_HIDE, 
       ewWaitUntilTerminated, ResultCode);
  
  // 结束 aria2c.exe 进程
  Log('尝试结束 aria2c.exe...');
  Exec('taskkill.exe', '/f /im aria2c.exe', '', SW_HIDE, 
       ewWaitUntilTerminated, ResultCode);
  
  // 等待1秒确保进程完全退出
  Sleep(1000);
  
  Log('进程清理操作完成');
end;

function InitializeUninstall(): Boolean;
var
  ResultCode: Integer;
begin
  Result := True;
  Log('卸载初始化，结束相关进程...');
  // 结束 R.E.P.O.Launcher.exe 进程
  Log('尝试结束 R.E.P.O.Launcher.exe...');
  Exec('taskkill.exe', '/f /im R.E.P.O.Launcher.exe', '', SW_HIDE, 
       ewWaitUntilTerminated, ResultCode);
  
  // 结束 aria2c.exe 进程
  Log('尝试结束 aria2c.exe...');
  Exec('taskkill.exe', '/f /im aria2c.exe', '', SW_HIDE, 
       ewWaitUntilTerminated, ResultCode);
  
  // 等待1秒确保进程完全退出
  Sleep(1000);
end;

[Languages]
Name: "ChineseSimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "D:\SteamLibrary\steamapps\common\REPO\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:ProgramOnTheWeb,{#MyAppName}}"; Filename: "{#MyAppURL}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[InstallDelete]
;删除文件，{app}：安装目录
Type: files; Name: "{app}\doorstop_config.ini";
Type: files; Name: "{app}\version.json";
Type: files; Name: "{app}\winhttp.dll";
;删除文件夹
Type: filesandordirs; Name: "{app}\BepInEx";
Type: filesandordirs; Name: "{app}\config";
Type: filesandordirs; Name: "{app}\logs";

[UninstallDelete]
;删除文件，{app}：安装目录
Type: files; Name: "{app}\doorstop_config.ini";
Type: files; Name: "{app}\version.json";
Type: files; Name: "{app}\winhttp.dll";
;删除文件夹
Type: filesandordirs; Name: "{app}\BepInEx";
Type: filesandordirs; Name: "{app}\config";
Type: filesandordirs; Name: "{app}\logs";

